[project]
name = "pepit-eigac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "mosek>=11.0.22",
    "numpy>=2.3.0",
    "pepit>=0.3.2",
    "scikit-learn>=1.7.0",
]
